version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: parker-db
    environment:
      POSTGRES_USER: parker
      POSTGRES_PASSWORD: parker
      POSTGRES_DB: parker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../apps/api/src/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  postgres_data:
